const products = [
  {
    id: "1",
    title: "Áo phông trắng",
    image: "https://picsum.photos/seed/1/200/200",
    price: 200000,
    description: "Áo phông trắng cổ tròn, chất liệu cotton thoáng mát.",
    category: "Áo phông",
  },
  {
    id: "2",
    title: "Quần short jeans",
    image: "https://picsum.photos/seed/2/200/200",
    price: 300000,
    description: "Quần short jeans xanh, thiết kế trẻ trung, năng động.",
    category: "Quần short",
  },
  {
    id: "3",
    title: "Váy maxi hoa",
    image: "https://picsum.photos/seed/3/200/200",
    price: 450000,
    description: "Váy maxi họa tiết hoa, chất liệu nhẹ nhàng, thoải mái.",
    category: "Váy",
  },
  {
    id: "4",
    title: "Áo hai dây",
    image: "https://picsum.photos/seed/4/200/200",
    price: 180000,
    description: "Áo hai dây màu trắng, thiết kế đơn giản, dễ phối đồ.",
    category: "Áo",
  },
  {
    id: "5",
    title: "Quần short kaki",
    image: "https://picsum.photos/seed/5/200/200",
    price: 320000,
    description:
      "Quần short kaki màu beige, thích hợp cho các hoạt động ngoài trời.",
    category: "Quần short",
  },
  {
    id: "6",
    title: "Áo sơ mi ngắn tay",
    image: "https://picsum.photos/seed/6/200/200",
    price: 250000,
    description: "Áo sơ mi ngắn tay màu xanh dương, chất liệu cotton.",
    category: "Áo sơ mi",
  },
  {
    id: "7",
    title: "Váy ngắn chữ A",
    image: "https://picsum.photos/seed/7/200/200",
    price: 400000,
    description: "Váy ngắn chữ A màu đen, thiết kế đơn giản, thanh lịch.",
    category: "Váy",
  },
  {
    id: "8",
    title: "Áo crop top",
    image: "https://picsum.photos/seed/8/200/200",
    price: 200000,
    description: "Áo crop top màu hồng pastel, chất liệu thun co giãn.",
    category: "Áo",
  },
  {
    id: "9",
    title: "Quần legging thể thao",
    image: "https://picsum.photos/seed/9/200/200",
    price: 350000,
    description:
      "Quần legging thể thao màu đen, chất liệu co giãn, thoáng mát.",
    category: "Quần",
  },
  {
    id: "10",
    title: "Đầm công sở",
    image: "https://picsum.photos/seed/10/200/200",
    price: 500000,
    description: "Đầm công sở màu xanh navy, thiết kế ôm dáng, thanh lịch.",
    category: "Đầm",
  },
  {
    id: "11",
    title: "Áo polo",
    image: "https://picsum.photos/seed/11/200/200",
    price: 270000,
    description: "Áo polo màu xám, chất liệu cotton thoáng mát.",
    category: "Áo polo",
  },
  {
    id: "12",
    title: "Quần jogger",
    image: "https://picsum.photos/seed/12/200/200",
    price: 380000,
    description:
      "Quần jogger màu đen, chất liệu vải dù, thoải mái khi vận động.",
    category: "Quần jogger",
  },
  {
    id: "13",
    title: "Áo sơ mi hoa",
    image: "https://picsum.photos/seed/13/200/200",
    price: 300000,
    description: "Áo sơ mi hoa màu trắng, thiết kế trẻ trung, năng động.",
    category: "Áo sơ mi",
  },
  {
    id: "14",
    title: "Váy yếm",
    image: "https://picsum.photos/seed/14/200/200",
    price: 450000,
    description: "Váy yếm màu xanh denim, thiết kế cá tính, thời trang.",
    category: "Váy yếm",
  },
  {
    id: "15",
    title: "Áo khoác mỏng",
    image: "https://picsum.photos/seed/15/200/200",
    price: 400000,
    description: "Áo khoác mỏng màu trắng, chất liệu dù chống nắng.",
    category: "Áo khoác",
  },
];
